In [3]:
from pathlib import Path

print("Current working directory:")
print(Path.cwd())

print("\nFiles/folders here:")
for item in Path.cwd().iterdir():
    print(item)

Current working directory:
c:\Users\hp\OneDrive\Desktop\Entity Extraction

Files/folders here:
c:\Users\hp\OneDrive\Desktop\Entity Extraction\data
c:\Users\hp\OneDrive\Desktop\Entity Extraction\notebooks
c:\Users\hp\OneDrive\Desktop\Entity Extraction\venv

In [4]:
from pathlib import Path

matches = list(Path.cwd().rglob("schemesathi_entity_dataset_2000*.csv"))

print("Found files:")
for file in matches:
    print(file)

Found files:
c:\Users\hp\OneDrive\Desktop\Entity Extraction\data\schemesathi_entity_dataset_2000.csv

In [5]:
import pandas as pd

DATA_PATH = r"C:\Users\hp\OneDrive\Desktop\Entity Extraction\data\schemesathi_entity_dataset_2000.csv"

df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Dataset shape: (2000, 9)

Columns:
['transcript_id', 'user_transcript', 'age', 'gender', 'annual_income', 'occupation', 'state', 'caste_category', 'is_differently_abled']

First 5 rows:

,transcript_id,user_transcript,age,gender,annual_income,occupation,state,caste_category,is_differently_abled
0,T0001,I am a 60 year old male berojgar living in Mad...,60,Male,120000.0,berojgar,Madhya Pradesh,NaN,False
1,T0002,"Main Uttar Pradesh se ek daily wage worker hu,...",26,NaN,45000.0,daily wage worker,Uttar Pradesh,NaN,False
2,T0003,I am a 61 year old female unemployed living in...,61,Female,350000.0,unemployed,Maharashtra,NaN,False
3,T0004,"Namaste, main 25 varsh ka berojgar hu West Ben...",25,NaN,0.0,berojgar,West Bengal,General,True
4,T0005,"Hi, I am 33 years old student from Maharashtra...",33,NaN,45000.0,kisan,Maharashtra,NaN,True

In [6]:
print("===== MISSING VALUES =====")
print(df.isnull().sum())

print("\n===== DATA TYPES =====")
print(df.dtypes)

print("\n===== UNIQUE VALUES =====")

for column in df.columns:
    if column != "user_transcript":
        print(f"\n--- {column} ---")
        print(df[column].dropna().unique()[:30])

===== MISSING VALUES =====
transcript_id              0
user_transcript            0
age                        0
gender                  1336
annual_income              0
occupation                 0
state                      0
caste_category           983
is_differently_abled       0
dtype: int64

===== DATA TYPES =====
transcript_id            object
user_transcript          object
age                       int64
gender                   object
annual_income           float64
occupation               object
state                    object
caste_category           object
is_differently_abled       bool
dtype: object

===== UNIQUE VALUES =====

--- transcript_id ---
['T0001' 'T0002' 'T0003' 'T0004' 'T0005' 'T0006' 'T0007' 'T0008' 'T0009'
 'T0010' 'T0011' 'T0012' 'T0013' 'T0014' 'T0015' 'T0016' 'T0017' 'T0018'
 'T0019' 'T0020' 'T0021' 'T0022' 'T0023' 'T0024' 'T0025' 'T0026' 'T0027'
 'T0028' 'T0029' 'T0030']

--- age ---
[60 26 61 25 33 34 63 41 51 19 20 31 43 52 28 62 21 39 44 35 58 65 45 64
 29 55 49 54 32 48]

--- gender ---
['Male' 'Female']

--- annual_income ---
[120000.  45000. 350000.      0. 200000. 600000.  80000.]

--- occupation ---
['berojgar' 'daily wage worker' 'unemployed' 'kisan' 'farmer' 'labour'
 'bunkar' 'artisan' 'weaver' 'student' 'mazdoor' 'rehri wala'
 'street vendor' 'chhatra']

--- state ---
['Madhya Pradesh' 'Uttar Pradesh' 'Maharashtra' 'West Bengal' 'Bihar'
 'Tamil Nadu' 'Karnataka' 'Rajasthan']

--- caste_category ---
['General' 'ST' 'OBC' 'SC']

--- is_differently_abled ---
[False  True]

In [7]:
ENTITY_COLUMNS = {
    "age": "AGE",
    "gender": "GENDER",
    "annual_income": "ANNUAL_INCOME",
    "occupation": "OCCUPATION",
    "state": "STATE",
    "caste_category": "CASTE_CATEGORY",
    "is_differently_abled": "DISABILITY"
}

print("Entity types:")
for column, entity in ENTITY_COLUMNS.items():
    print(f"{column} → {entity}")

Entity types:
age → AGE
gender → GENDER
annual_income → ANNUAL_INCOME
occupation → OCCUPATION
state → STATE
caste_category → CASTE_CATEGORY
is_differently_abled → DISABILITY

In [8]:
pd.set_option("display.max_colwidth", 300)

display(
    df[
        [
            "user_transcript",
            "age",
            "gender",
            "annual_income",
            "occupation",
            "state",
            "caste_category",
            "is_differently_abled"
        ]
    ].head(20)
)

,user_transcript,age,gender,annual_income,occupation,state,caste_category,is_differently_abled
0,I am a 60 year old male berojgar living in Madhya Pradesh. My annual household income is 120000 rupees.,60,Male,120000.0,berojgar,Madhya Pradesh,NaN,False
1,"Main Uttar Pradesh se ek daily wage worker hu, meri umar 26 saal hai aur saalana kamai 45000 rupe hai.",26,NaN,45000.0,daily wage worker,Uttar Pradesh,NaN,False
2,I am a 61 year old female unemployed living in Maharashtra. My annual household income is 350000 rupees.,61,Female,350000.0,unemployed,Maharashtra,NaN,False
3,"Namaste, main 25 varsh ka berojgar hu West Bengal se. Meri income 0 rupaye hai, aur main General varg se hoon. Main divyang hu.",25,NaN,0.0,berojgar,West Bengal,General,True
4,"Hi, I am 33 years old student from Maharashtra. My family income is 45000 and I am differently abled.",33,NaN,45000.0,kisan,Maharashtra,NaN,True
5,"Namaste, main 34 varsh ka berojgar hu Uttar Pradesh se. Meri income 45000 rupaye hai, aur main ST varg se hoon. Main divyang hu.",34,NaN,45000.0,berojgar,Uttar Pradesh,ST,True
6,"Namaste, main 63 varsh ka farmer hu Bihar se. Meri income 200000 rupaye hai, aur main General varg se hoon. Main divyang hu.",63,NaN,200000.0,farmer,Bihar,General,True
7,I am a 25 year old male labour living in West Bengal. My annual household income is 600000 rupees.,25,Male,600000.0,labour,West Bengal,NaN,False
8,"Mera naam Ramesh hai, main Tamil Nadu ka rehne wala hu. Main OBC category se ek mahila hu aur bunkar hu. Aamdani 80000 per year hai.",41,Female,80000.0,bunkar,Tamil Nadu,OBC,False
9,"Namaste, main 51 varsh ka artisan hu Uttar Pradesh se. Meri income 350000 rupaye hai, aur main SC varg se hoon. Main divyang hu.",51,NaN,350000.0,artisan,Uttar Pradesh,SC,True
10,"I belong to OBC category from West Bengal. Age is 19, profession is artisan, income around 120000.",19,NaN,120000.0,artisan,West Bengal,OBC,False
11,"Namaste, main 20 varsh ka weaver hu Uttar Pradesh se. Meri income 45000 rupaye hai, aur main OBC varg se hoon. Main divyang hu.",20,NaN,45000.0,weaver,Uttar Pradesh,OBC,True
12,"Mera naam Ramesh hai, main Bihar ka rehne wala hu. Main SC category se ek purush hu aur student hu. Aamdani 350000 per year hai.",31,Male,350000.0,student,Bihar,SC,False
13,I am a 43 year old male artisan living in Bihar. My annual household income is 0 rupees.,43,Male,0.0,artisan,Bihar,NaN,False
14,"Main Karnataka se ek unemployed hu, meri umar 52 saal hai aur saalana kamai 0 rupe hai.",52,NaN,0.0,unemployed,Karnataka,NaN,False
15,"I belong to General category from West Bengal. Age is 28, profession is kisan, income around 0.",28,NaN,0.0,kisan,West Bengal,General,False
16,"Namaste, main 62 varsh ka berojgar hu Bihar se. Meri income 80000 rupaye hai, aur main SC varg se hoon. Main divyang hu.",62,NaN,80000.0,berojgar,Bihar,SC,True
17,"I belong to SC category from Madhya Pradesh. Age is 21, profession is labour, income around 120000.",21,NaN,120000.0,labour,Madhya Pradesh,SC,False
18,"Main Karnataka se ek artisan hu, meri umar 39 saal hai aur saalana kamai 120000 rupe hai.",39,NaN,120000.0,artisan,Karnataka,NaN,False
19,I am a 44 year old male mazdoor living in Bihar. My annual household income is 600000 rupees.,44,Male,600000.0,mazdoor,Bihar,NaN,False

In [9]:
import re

def tokenize(text):
    """
    Split a transcript into words/numbers while keeping
    Hindi/English words and decimal numbers.
    """
    return re.findall(r'\d+(?:\.\d+)?|[A-Za-zÀ-ÿ]+', str(text))

# Test
test_text = df.loc[1, "user_transcript"]

print(test_text)
print(tokenize(test_text))

Main Uttar Pradesh se ek daily wage worker hu, meri umar 26 saal hai aur saalana kamai 45000 rupe hai.
['Main', 'Uttar', 'Pradesh', 'se', 'ek', 'daily', 'wage', 'worker', 'hu', 'meri', 'umar', '26', 'saal', 'hai', 'aur', 'saalana', 'kamai', '45000', 'rupe', 'hai']

In [10]:
def normalize(text):
    text = str(text).lower().strip()
    text = re.sub(r'[^\w\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()


print(normalize("Madhya Pradesh."))
print(normalize("Uttar Pradesh"))
print(normalize("Daily Wage Worker"))

madhya pradesh
uttar pradesh
daily wage worker

In [11]:
def find_entity_tokens(tokens, entity_value):
    """
    Find an entity value inside a tokenized sentence.
    Returns the start and end token positions.
    """

    if pd.isna(entity_value):
        return None

    entity_tokens = tokenize(str(entity_value))

    if not entity_tokens:
        return None

    normalized_entity = [normalize(t) for t in entity_tokens]

    for i in range(len(tokens) - len(normalized_entity) + 1):
        window = [normalize(t) for t in tokens[i:i + len(normalized_entity)]]

        if window == normalized_entity:
            return i, i + len(normalized_entity)

    return None

In [12]:
# Take one example
row = df.iloc[1]

tokens = tokenize(row["user_transcript"])

print("Tokens:")
print(tokens)

print("\nOccupation:")
print(row["occupation"])

print("\nOccupation position:")
print(find_entity_tokens(tokens, row["occupation"]))

print("\nState:")
print(row["state"])

print("\nState position:")
print(find_entity_tokens(tokens, row["state"]))

Tokens:
['Main', 'Uttar', 'Pradesh', 'se', 'ek', 'daily', 'wage', 'worker', 'hu', 'meri', 'umar', '26', 'saal', 'hai', 'aur', 'saalana', 'kamai', '45000', 'rupe', 'hai']

Occupation:
daily wage worker

Occupation position:
(5, 8)

State:
Uttar Pradesh

State position:
(1, 3)

In [13]:
def add_entity_labels(tokens, labels, entity_value, entity_type):
    """
    Find an entity in the token list and assign BIO labels.
    """

    position = find_entity_tokens(tokens, entity_value)

    if position is None:
        return

    start, end = position

    # B = beginning of entity
    labels[start] = f"B-{entity_type}"

    # I = inside entity
    for i in range(start + 1, end):
        labels[i] = f"I-{entity_type}"

In [14]:
row = df.iloc[1]

tokens = tokenize(row["user_transcript"])

# Initially everything is O
labels = ["O"] * len(tokens)

# Add occupation
add_entity_labels(
    tokens,
    labels,
    row["occupation"],
    "OCCUPATION"
)

# Add state
add_entity_labels(
    tokens,
    labels,
    row["state"],
    "STATE"
)

# Display token + label
for token, label in zip(tokens, labels):
    print(f"{token:15} {label}")

Main            O
Uttar           B-STATE
Pradesh         I-STATE
se              O
ek              O
daily           B-OCCUPATION
wage            I-OCCUPATION
worker          I-OCCUPATION
hu              O
meri            O
umar            O
26              O
saal            O
hai             O
aur             O
saalana         O
kamai           O
45000           O
rupe            O
hai             O

In [15]:
def find_numeric_entity(tokens, value):
    """
    Find a numeric value inside the tokenized transcript.
    """

    if pd.isna(value):
        return None

    # Convert values like 26.0 -> 26
    if isinstance(value, float) and value.is_integer():
        value = int(value)

    value = str(value).strip()

    for i, token in enumerate(tokens):
        # Remove punctuation for comparison
        clean_token = re.sub(r'[^\d.]', '', token)

        if clean_token == value:
            return i, i + 1

    return None

In [16]:
row = df.iloc[1]

tokens = tokenize(row["user_transcript"])
labels = ["O"] * len(tokens)

# State
add_entity_labels(
    tokens,
    labels,
    row["state"],
    "STATE"
)

# Occupation
add_entity_labels(
    tokens,
    labels,
    row["occupation"],
    "OCCUPATION"
)

# Age
age_position = find_numeric_entity(tokens, row["age"])

if age_position:
    start, end = age_position
    labels[start] = "B-AGE"

# Annual income
income_position = find_numeric_entity(tokens, row["annual_income"])

if income_position:
    start, end = income_position
    labels[start] = "B-ANNUAL_INCOME"

# Display
for token, label in zip(tokens, labels):
    print(f"{token:15} {label}")

Main            O
Uttar           B-STATE
Pradesh         I-STATE
se              O
ek              O
daily           B-OCCUPATION
wage            I-OCCUPATION
worker          I-OCCUPATION
hu              O
meri            O
umar            O
26              B-AGE
saal            O
hai             O
aur             O
saalana         O
kamai           O
45000           B-ANNUAL_INCOME
rupe            O
hai             O

In [17]:
# Keywords used to identify disability in the transcript

DISABILITY_KEYWORDS = [
    "divyang",
    "differently abled",
    "differently-abled",
    "disabled",
    "disability"
]


def find_keyword_entity(tokens, keywords):
    """
    Find the first matching keyword/phrase in the token list.
    """
    for keyword in keywords:
        position = find_entity_tokens(tokens, keyword)

        if position is not None:
            return position

    return None

In [18]:
row = df.iloc[3]

tokens = tokenize(row["user_transcript"])
labels = ["O"] * len(tokens)

# STATE
add_entity_labels(
    tokens,
    labels,
    row["state"],
    "STATE"
)

# OCCUPATION
add_entity_labels(
    tokens,
    labels,
    row["occupation"],
    "OCCUPATION"
)

# AGE
age_position = find_numeric_entity(tokens, row["age"])

if age_position:
    start, end = age_position
    labels[start] = "B-AGE"

# INCOME
income_position = find_numeric_entity(tokens, row["annual_income"])

if income_position:
    start, end = income_position
    labels[start] = "B-ANNUAL_INCOME"

# GENDER
if not pd.isna(row["gender"]):
    add_entity_labels(
        tokens,
        labels,
        row["gender"],
        "GENDER"
    )

# CASTE
if not pd.isna(row["caste_category"]):
    add_entity_labels(
        tokens,
        labels,
        row["caste_category"],
        "CASTE_CATEGORY"
    )

# DISABILITY
if row["is_differently_abled"] == True:
    disability_position = find_keyword_entity(
        tokens,
        DISABILITY_KEYWORDS
    )

    if disability_position:
        start, end = disability_position

        labels[start] = "B-DISABILITY"

        for i in range(start + 1, end):
            labels[i] = "I-DISABILITY"


# Display
for token, label in zip(tokens, labels):
    print(f"{token:15} {label}")

Namaste         O
main            O
25              B-AGE
varsh           O
ka              O
berojgar        B-OCCUPATION
hu              O
West            B-STATE
Bengal          I-STATE
se              O
Meri            O
income          O
0               B-ANNUAL_INCOME
rupaye          O
hai             O
aur             O
main            O
General         B-CASTE_CATEGORY
varg            O
se              O
hoon            O
Main            O
divyang         B-DISABILITY
hu              O

In [19]:
GENDER_KEYWORDS = [
    "male",
    "female",
    "man",
    "woman",
    "purush",
    "mahila",
    "aadmi",
    "aurat"
]

CASTE_KEYWORDS = [
    "general",
    "obc",
    "sc",
    "st"
]

DISABILITY_KEYWORDS = [
    "divyang",
    "differently abled",
    "differently-abled",
    "disabled",
    "disability"
]

In [20]:
def add_keyword_entity(tokens, labels, keywords, entity_type):
    """
    Find and label the first occurrence of a keyword/phrase.
    """
    position = find_keyword_entity(tokens, keywords)

    if position is None:
        return

    start, end = position

    # Don't overwrite an existing entity
    if any(label != "O" for label in labels[start:end]):
        return

    labels[start] = f"B-{entity_type}"

    for i in range(start + 1, end):
        labels[i] = f"I-{entity_type}"

In [21]:
# Find rows where gender is missing
gender_missing = df[df["gender"].isna()]

# Display first 10
display(
    gender_missing[
        ["user_transcript", "gender"]
    ].head(10)
)

,user_transcript,gender
1,"Main Uttar Pradesh se ek daily wage worker hu, meri umar 26 saal hai aur saalana kamai 45000 rupe hai.",NaN
3,"Namaste, main 25 varsh ka berojgar hu West Bengal se. Meri income 0 rupaye hai, aur main General varg se hoon. Main divyang hu.",NaN
4,"Hi, I am 33 years old student from Maharashtra. My family income is 45000 and I am differently abled.",NaN
5,"Namaste, main 34 varsh ka berojgar hu Uttar Pradesh se. Meri income 45000 rupaye hai, aur main ST varg se hoon. Main divyang hu.",NaN
6,"Namaste, main 63 varsh ka farmer hu Bihar se. Meri income 200000 rupaye hai, aur main General varg se hoon. Main divyang hu.",NaN
9,"Namaste, main 51 varsh ka artisan hu Uttar Pradesh se. Meri income 350000 rupaye hai, aur main SC varg se hoon. Main divyang hu.",NaN
10,"I belong to OBC category from West Bengal. Age is 19, profession is artisan, income around 120000.",NaN
11,"Namaste, main 20 varsh ka weaver hu Uttar Pradesh se. Meri income 45000 rupaye hai, aur main OBC varg se hoon. Main divyang hu.",NaN
14,"Main Karnataka se ek unemployed hu, meri umar 52 saal hai aur saalana kamai 0 rupe hai.",NaN
15,"I belong to General category from West Bengal. Age is 28, profession is kisan, income around 0.",NaN

In [22]:
def convert_row_to_bio(row):
    """
    Convert one dataset row into token-level BIO annotations.
    """

    text = row["user_transcript"]
    tokens = tokenize(text)

    # Initially every token is outside an entity
    labels = ["O"] * len(tokens)

    # --------------------------------------------------
    # 1. STATE
    # --------------------------------------------------
    add_keyword_entity(
        tokens,
        labels,
        [str(row["state"])],
        "STATE"
    )

    # --------------------------------------------------
    # 2. OCCUPATION
    # --------------------------------------------------
    if not pd.isna(row["occupation"]):
        add_keyword_entity(
            tokens,
            labels,
            [str(row["occupation"])],
            "OCCUPATION"
        )

    # --------------------------------------------------
    # 3. AGE
    # --------------------------------------------------
    age_position = find_numeric_entity(
        tokens,
        row["age"]
    )

    if age_position:
        start, end = age_position

        if all(label == "O" for label in labels[start:end]):
            labels[start] = "B-AGE"

            for i in range(start + 1, end):
                labels[i] = "I-AGE"

    # --------------------------------------------------
    # 4. ANNUAL INCOME
    # --------------------------------------------------
    income_position = find_numeric_entity(
        tokens,
        row["annual_income"]
    )

    if income_position:
        start, end = income_position

        if all(label == "O" for label in labels[start:end]):
            labels[start] = "B-ANNUAL_INCOME"

            for i in range(start + 1, end):
                labels[i] = "I-ANNUAL_INCOME"

    # --------------------------------------------------
    # 5. GENDER
    # --------------------------------------------------
    if not pd.isna(row["gender"]):
        add_keyword_entity(
            tokens,
            labels,
            [str(row["gender"])],
            "GENDER"
        )

    # --------------------------------------------------
    # 6. CASTE CATEGORY
    # --------------------------------------------------
    if not pd.isna(row["caste_category"]):
        add_keyword_entity(
            tokens,
            labels,
            [str(row["caste_category"])],
            "CASTE_CATEGORY"
        )

    # --------------------------------------------------
    # 7. DISABILITY
    # --------------------------------------------------
    if row["is_differently_abled"] == True:
        add_keyword_entity(
            tokens,
            labels,
            DISABILITY_KEYWORDS,
            "DISABILITY"
        )

    return tokens, labels

In [23]:
row = df.iloc[3]

tokens, labels = convert_row_to_bio(row)

for token, label in zip(tokens, labels):
    print(f"{token:15} {label}")

Namaste         O
main            O
25              B-AGE
varsh           O
ka              O
berojgar        B-OCCUPATION
hu              O
West            B-STATE
Bengal          I-STATE
se              O
Meri            O
income          O
0               B-ANNUAL_INCOME
rupaye          O
hai             O
aur             O
main            O
General         B-CASTE_CATEGORY
varg            O
se              O
hoon            O
Main            O
divyang         B-DISABILITY
hu              O

In [24]:
# Test BIO conversion on the complete dataset

all_results = []

for idx, row in df.iterrows():
    tokens, labels = convert_row_to_bio(row)

    all_results.append({
        "transcript_id": row["transcript_id"],
        "tokens": tokens,
        "labels": labels
    })

print("Total rows converted:", len(all_results))
print("First row:")
print(all_results[0])

Total rows converted: 2000
First row:
{'transcript_id': 'T0001', 'tokens': ['I', 'am', 'a', '60', 'year', 'old', 'male', 'berojgar', 'living', 'in', 'Madhya', 'Pradesh', 'My', 'annual', 'household', 'income', 'is', '120000', 'rupees'], 'labels': ['O', 'O', 'O', 'B-AGE', 'O', 'O', 'B-GENDER', 'B-OCCUPATION', 'O', 'O', 'B-STATE', 'I-STATE', 'O', 'O', 'O', 'O', 'O', 'B-ANNUAL_INCOME', 'O']}

In [25]:
from collections import Counter

label_counter = Counter()

for item in all_results:
    label_counter.update(item["labels"])

# Convert to DataFrame for better view
label_df = pd.DataFrame(
    label_counter.items(),
    columns=["Label", "Count"]
).sort_values("Count", ascending=False)

display(label_df)

               Label  Count
0                  O  29624
4            B-STATE   2000
6    B-ANNUAL_INCOME   2000
3       B-OCCUPATION   1690
1              B-AGE   1674
8   B-CASTE_CATEGORY   1017
5            I-STATE    989
9       B-DISABILITY    685
7       I-OCCUPATION    476
2           B-GENDER    338
10      I-DISABILITY    337

In [26]:
missing_age = []

for idx, row in df.iterrows():

    tokens = tokenize(row["user_transcript"])
    position = find_numeric_entity(tokens, row["age"])

    if position is None:
        missing_age.append({
            "transcript_id": row["transcript_id"],
            "text": row["user_transcript"],
            "age": row["age"]
        })

print("Missing AGE matches:", len(missing_age))

display(pd.DataFrame(missing_age).head(20))

Missing AGE matches: 326

,transcript_id,text,age
0,T0009,"Mera naam Ramesh hai, main Tamil Nadu ka rehne wala hu. Main OBC category se ek mahila hu aur bunkar hu. Aamdani 80000 per year hai.",41
1,T0013,"Mera naam Ramesh hai, main Bihar ka rehne wala hu. Main SC category se ek purush hu aur student hu. Aamdani 350000 per year hai.",31
2,T0034,"Mera naam Ramesh hai, main Tamil Nadu ka rehne wala hu. Main OBC category se ek purush hu aur artisan hu. Aamdani 0 per year hai.",49
3,T0039,"Mera naam Ramesh hai, main Karnataka ka rehne wala hu. Main General category se ek mahila hu aur weaver hu. Aamdani 0 per year hai.",39
4,T0044,"Mera naam Ramesh hai, main Karnataka ka rehne wala hu. Main ST category se ek purush hu aur street vendor hu. Aamdani 350000 per year hai.",48
5,T0047,"Mera naam Ramesh hai, main Bihar ka rehne wala hu. Main General category se ek mahila hu aur bunkar hu. Aamdani 80000 per year hai.",31
6,T0056,"Mera naam Ramesh hai, main Karnataka ka rehne wala hu. Main General category se ek mahila hu aur daily wage worker hu. Aamdani 200000 per year hai.",62
7,T0059,"Mera naam Ramesh hai, main West Bengal ka rehne wala hu. Main General category se ek mahila hu aur rehri wala hu. Aamdani 600000 per year hai.",36
8,T0063,"Mera naam Ramesh hai, main Rajasthan ka rehne wala hu. Main OBC category se ek purush hu aur labour hu. Aamdani 350000 per year hai.",30
9,T0073,"Mera naam Ramesh hai, main Uttar Pradesh ka rehne wala hu. Main General category se ek purush hu aur student hu. Aamdani 120000 per year hai.",43
10,T0075,"Mera naam Ramesh hai, main Madhya Pradesh ka rehne wala hu. Main General category se ek mahila hu aur mazdoor hu. Aamdani 120000 per year hai.",39
11,T0081,"Mera naam Ramesh hai, main Rajasthan ka rehne wala hu. Main ST category se ek mahila hu aur labour hu. Aamdani 350000 per year hai.",42
12,T0095,"Mera naam Ramesh hai, main Uttar Pradesh ka rehne wala hu. Main ST category se ek mahila hu aur unemployed hu. Aamdani 45000 per year hai.",56
13,T0096,"Mera naam Ramesh hai, main Uttar Pradesh ka rehne wala hu. Main OBC category se ek mahila hu aur unemployed hu. Aamdani 600000 per year hai.",18
14,T0097,"Mera naam Ramesh hai, main Tamil Nadu ka rehne wala hu. Main OBC category se ek mahila hu aur farmer hu. Aamdani 80000 per year hai.",45
15,T0120,"Mera naam Ramesh hai, main Karnataka ka rehne wala hu. Main ST category se ek purush hu aur mazdoor hu. Aamdani 600000 per year hai.",65
16,T0128,"Mera naam Ramesh hai, main Uttar Pradesh ka rehne wala hu. Main ST category se ek mahila hu aur kisan hu. Aamdani 120000 per year hai.",32
17,T0130,"Mera naam Ramesh hai, main Rajasthan ka rehne wala hu. Main ST category se ek purush hu aur weaver hu. Aamdani 0 per year hai.",42
18,T0131,"Mera naam Ramesh hai, main Bihar ka rehne wala hu. Main ST category se ek mahila hu aur rehri wala hu. Aamdani 350000 per year hai.",42
19,T0133,"Mera naam Ramesh hai, main Bihar ka rehne wala hu. Main ST category se ek mahila hu aur bunkar hu. Aamdani 600000 per year hai.",45

In [27]:
missing_occupation = []

for idx, row in df.iterrows():

    tokens = tokenize(row["user_transcript"])

    position = find_entity_tokens(
        tokens,
        row["occupation"]
    )

    if position is None:
        missing_occupation.append({
            "transcript_id": row["transcript_id"],
            "text": row["user_transcript"],
            "occupation": row["occupation"]
        })

print("Missing OCCUPATION matches:", len(missing_occupation))

display(pd.DataFrame(missing_occupation).head(20))

Missing OCCUPATION matches: 310

,transcript_id,text,occupation
0,T0005,"Hi, I am 33 years old student from Maharashtra. My family income is 45000 and I am differently abled.",kisan
1,T0022,"Hi, I am 58 years old student from West Bengal. My family income is 120000 and I am differently abled.",bunkar
2,T0025,"Hi, I am 62 years old student from West Bengal. My family income is 120000 and I am differently abled.",rehri wala
3,T0026,"Hi, I am 65 years old student from Uttar Pradesh. My family income is 200000 and I am differently abled.",labour
4,T0028,"Hi, I am 51 years old student from Bihar. My family income is 80000 and I am differently abled.",bunkar
5,T0029,"Hi, I am 65 years old student from Madhya Pradesh. My family income is 0 and I am differently abled.",weaver
6,T0033,"Hi, I am 55 years old student from Maharashtra. My family income is 350000 and I am differently abled.",bunkar
7,T0038,"Hi, I am 54 years old student from Bihar. My family income is 600000 and I am differently abled.",bunkar
8,T0042,"Hi, I am 62 years old student from Bihar. My family income is 200000 and I am differently abled.",chhatra
9,T0048,"Hi, I am 53 years old student from West Bengal. My family income is 350000 and I am differently abled.",daily wage worker
10,T0050,"Hi, I am 51 years old student from Tamil Nadu. My family income is 120000 and I am differently abled.",weaver
11,T0064,"Hi, I am 22 years old student from Madhya Pradesh. My family income is 120000 and I am differently abled.",farmer
12,T0082,"Hi, I am 38 years old student from Tamil Nadu. My family income is 200000 and I am differently abled.",daily wage worker
13,T0086,"Hi, I am 43 years old student from Madhya Pradesh. My family income is 350000 and I am differently abled.",unemployed
14,T0089,"Hi, I am 65 years old student from Uttar Pradesh. My family income is 600000 and I am differently abled.",bunkar
15,T0090,"Hi, I am 60 years old student from West Bengal. My family income is 600000 and I am differently abled.",rehri wala
16,T0093,"Hi, I am 26 years old student from Madhya Pradesh. My family income is 45000 and I am differently abled.",unemployed
17,T0103,"Hi, I am 18 years old student from Rajasthan. My family income is 120000 and I am differently abled.",rehri wala
18,T0108,"Hi, I am 54 years old student from Bihar. My family income is 45000 and I am differently abled.",farmer
19,T0110,"Hi, I am 63 years old student from Maharashtra. My family income is 80000 and I am differently abled.",daily wage worker

In [28]:
# Check whether each structured entity is actually mentioned
# in its corresponding transcript

entity_match_stats = {
    "AGE": 0,
    "GENDER": 0,
    "OCCUPATION": 0,
    "STATE": 0,
    "ANNUAL_INCOME": 0,
    "CASTE_CATEGORY": 0,
    "DISABILITY": 0
}

for _, row in df.iterrows():

    tokens = tokenize(row["user_transcript"])

    # AGE
    if find_numeric_entity(tokens, row["age"]) is not None:
        entity_match_stats["AGE"] += 1

    # GENDER
    if not pd.isna(row["gender"]):
        if find_entity_tokens(tokens, row["gender"]) is not None:
            entity_match_stats["GENDER"] += 1

    # OCCUPATION
    if find_entity_tokens(tokens, row["occupation"]) is not None:
        entity_match_stats["OCCUPATION"] += 1

    # STATE
    if find_entity_tokens(tokens, row["state"]) is not None:
        entity_match_stats["STATE"] += 1

    # INCOME
    if find_numeric_entity(tokens, row["annual_income"]) is not None:
        entity_match_stats["ANNUAL_INCOME"] += 1

    # CASTE
    if not pd.isna(row["caste_category"]):
        if find_entity_tokens(tokens, row["caste_category"]) is not None:
            entity_match_stats["CASTE_CATEGORY"] += 1

    # DISABILITY
    if row["is_differently_abled"] == True:
        if find_keyword_entity(tokens, DISABILITY_KEYWORDS) is not None:
            entity_match_stats["DISABILITY"] += 1


stats_df = pd.DataFrame(
    list(entity_match_stats.items()),
    columns=["Entity", "Matched_Rows"]
)

stats_df["Match_Percentage"] = (
    stats_df["Matched_Rows"] / len(df) * 100
).round(2)

display(stats_df)

           Entity  Matched_Rows  Match_Percentage
0             AGE          1674             83.70
1          GENDER           338             16.90
2      OCCUPATION          1690             84.50
3           STATE          2000            100.00
4   ANNUAL_INCOME          2000            100.00
5  CASTE_CATEGORY          1017             50.85
6      DISABILITY           685             34.25

In [29]:
# Show all transcripts where the structured age
# could not be found in the transcript

missing_age_df = pd.DataFrame(missing_age)

print("Total missing age matches:", len(missing_age_df))

display(
    missing_age_df[
        ["transcript_id", "text", "age"]
    ].head(30)
)

Total missing age matches: 326

,transcript_id,text,age
0,T0009,"Mera naam Ramesh hai, main Tamil Nadu ka rehne wala hu. Main OBC category se ek mahila hu aur bunkar hu. Aamdani 80000 per year hai.",41
1,T0013,"Mera naam Ramesh hai, main Bihar ka rehne wala hu. Main SC category se ek purush hu aur student hu. Aamdani 350000 per year hai.",31
2,T0034,"Mera naam Ramesh hai, main Tamil Nadu ka rehne wala hu. Main OBC category se ek purush hu aur artisan hu. Aamdani 0 per year hai.",49
3,T0039,"Mera naam Ramesh hai, main Karnataka ka rehne wala hu. Main General category se ek mahila hu aur weaver hu. Aamdani 0 per year hai.",39
4,T0044,"Mera naam Ramesh hai, main Karnataka ka rehne wala hu. Main ST category se ek purush hu aur street vendor hu. Aamdani 350000 per year hai.",48
5,T0047,"Mera naam Ramesh hai, main Bihar ka rehne wala hu. Main General category se ek mahila hu aur bunkar hu. Aamdani 80000 per year hai.",31
6,T0056,"Mera naam Ramesh hai, main Karnataka ka rehne wala hu. Main General category se ek mahila hu aur daily wage worker hu. Aamdani 200000 per year hai.",62
7,T0059,"Mera naam Ramesh hai, main West Bengal ka rehne wala hu. Main General category se ek mahila hu aur rehri wala hu. Aamdani 600000 per year hai.",36
8,T0063,"Mera naam Ramesh hai, main Rajasthan ka rehne wala hu. Main OBC category se ek purush hu aur labour hu. Aamdani 350000 per year hai.",30
9,T0073,"Mera naam Ramesh hai, main Uttar Pradesh ka rehne wala hu. Main General category se ek purush hu aur student hu. Aamdani 120000 per year hai.",43
10,T0075,"Mera naam Ramesh hai, main Madhya Pradesh ka rehne wala hu. Main General category se ek mahila hu aur mazdoor hu. Aamdani 120000 per year hai.",39
11,T0081,"Mera naam Ramesh hai, main Rajasthan ka rehne wala hu. Main ST category se ek mahila hu aur labour hu. Aamdani 350000 per year hai.",42
12,T0095,"Mera naam Ramesh hai, main Uttar Pradesh ka rehne wala hu. Main ST category se ek mahila hu aur unemployed hu. Aamdani 45000 per year hai.",56
13,T0096,"Mera naam Ramesh hai, main Uttar Pradesh ka rehne wala hu. Main OBC category se ek mahila hu aur unemployed hu. Aamdani 600000 per year hai.",18
14,T0097,"Mera naam Ramesh hai, main Tamil Nadu ka rehne wala hu. Main OBC category se ek mahila hu aur farmer hu. Aamdani 80000 per year hai.",45
15,T0120,"Mera naam Ramesh hai, main Karnataka ka rehne wala hu. Main ST category se ek purush hu aur mazdoor hu. Aamdani 600000 per year hai.",65
16,T0128,"Mera naam Ramesh hai, main Uttar Pradesh ka rehne wala hu. Main ST category se ek mahila hu aur kisan hu. Aamdani 120000 per year hai.",32
17,T0130,"Mera naam Ramesh hai, main Rajasthan ka rehne wala hu. Main ST category se ek purush hu aur weaver hu. Aamdani 0 per year hai.",42
18,T0131,"Mera naam Ramesh hai, main Bihar ka rehne wala hu. Main ST category se ek mahila hu aur rehri wala hu. Aamdani 350000 per year hai.",42
19,T0133,"Mera naam Ramesh hai, main Bihar ka rehne wala hu. Main ST category se ek mahila hu aur bunkar hu. Aamdani 600000 per year hai.",45
20,T0136,"Mera naam Ramesh hai, main Madhya Pradesh ka rehne wala hu. Main OBC category se ek mahila hu aur labour hu. Aamdani 200000 per year hai.",60
21,T0141,"Mera naam Ramesh hai, main Madhya Pradesh ka rehne wala hu. Main General category se ek purush hu aur weaver hu. Aamdani 0 per year hai.",32
22,T0148,"Mera naam Ramesh hai, main Uttar Pradesh ka rehne wala hu. Main OBC category se ek purush hu aur labour hu. Aamdani 0 per year hai.",23
23,T0153,"Mera naam Ramesh hai, main Uttar Pradesh ka rehne wala hu. Main General category se ek mahila hu aur artisan hu. Aamdani 350000 per year hai.",34
24,T0155,"Mera naam Ramesh hai, main Bihar ka rehne wala hu. Main SC category se ek mahila hu aur kisan hu. Aamdani 600000 per year hai.",34
25,T0163,"Mera naam Ramesh hai, main Karnataka ka rehne wala hu. Main ST category se ek purush hu aur chhatra hu. Aamdani 120000 per year hai.",22
26,T0164,"Mera naam Ramesh hai, main Karnataka ka rehne wala hu. Main ST category se ek purush hu aur unemployed hu. Aamdani 45000 per year hai.",23
27,T0169,"Mera naam Ramesh hai, main Tamil Nadu ka rehne wala hu. Main SC category se ek mahila hu aur student hu. Aamdani 45000 per year hai.",37
28,T0173,"Mera naam Ramesh hai, main West Bengal ka rehne wala hu. Main General category se ek mahila hu aur chhatra hu. Aamdani 0 per year hai.",24
29,T0177,"Mera naam Ramesh hai, main Rajasthan ka rehne wala hu. Main General category se ek purush hu aur bunkar hu. Aamdani 350000 per year hai.",43

In [30]:
# Find rows where the age number occurs more than once
# in the transcript.

ambiguous_age = []

for _, row in df.iterrows():

    tokens = tokenize(row["user_transcript"])

    age = row["age"]

    if isinstance(age, float) and age.is_integer():
        age = int(age)

    age_str = str(age)

    matches = []

    for i, token in enumerate(tokens):
        clean_token = re.sub(r'[^\d.]', '', token)

        if clean_token == age_str:
            matches.append(i)

    if len(matches) > 1:
        ambiguous_age.append({
            "transcript_id": row["transcript_id"],
            "text": row["user_transcript"],
            "age": age,
            "positions": matches
        })

print("Rows with multiple age-number matches:", len(ambiguous_age))

display(pd.DataFrame(ambiguous_age).head(20))

Rows with multiple age-number matches: 0

Empty DataFrame
Columns: []
Index: []

In [31]:
# Check how often gender-related words actually appear
# in the transcripts

gender_keywords_found = Counter()

for text in df["user_transcript"]:
    tokens = tokenize(text)

    for token in tokens:
        if normalize(token) in GENDER_KEYWORDS:
            gender_keywords_found[normalize(token)] += 1

print("Gender keywords found in transcripts:")
print(gender_keywords_found)

Gender keywords found in transcripts:
Counter({'male': 181, 'mahila': 164, 'purush': 162, 'female': 157})

In [32]:
def convert_row_to_bio(row):
    """
    Convert one dataset row into token-level BIO annotations.
    """

    text = row["user_transcript"]
    tokens = tokenize(text)

    labels = ["O"] * len(tokens)

    # 1. STATE
    add_keyword_entity(
        tokens,
        labels,
        [str(row["state"])],
        "STATE"
    )

    # 2. OCCUPATION
    if not pd.isna(row["occupation"]):
        add_keyword_entity(
            tokens,
            labels,
            [str(row["occupation"])],
            "OCCUPATION"
        )

    # 3. AGE
    age_position = find_numeric_entity(tokens, row["age"])

    if age_position:
        start, end = age_position

        if all(label == "O" for label in labels[start:end]):
            labels[start] = "B-AGE"

            for i in range(start + 1, end):
                labels[i] = "I-AGE"

    # 4. ANNUAL INCOME
    income_position = find_numeric_entity(tokens, row["annual_income"])

    if income_position:
        start, end = income_position

        if all(label == "O" for label in labels[start:end]):
            labels[start] = "B-ANNUAL_INCOME"

            for i in range(start + 1, end):
                labels[i] = "I-ANNUAL_INCOME"

    # 5. GENDER
    add_keyword_entity(
        tokens,
        labels,
        GENDER_KEYWORDS,
        "GENDER"
    )

    # 6. CASTE CATEGORY
    if not pd.isna(row["caste_category"]):
        add_keyword_entity(
            tokens,
            labels,
            [str(row["caste_category"])],
            "CASTE_CATEGORY"
        )

    # 7. DISABILITY
    if row["is_differently_abled"] == True:
        add_keyword_entity(
            tokens,
            labels,
            DISABILITY_KEYWORDS,
            "DISABILITY"
        )

    return tokens, labels

In [33]:
all_results = []

for idx, row in df.iterrows():
    tokens, labels = convert_row_to_bio(row)

    all_results.append({
        "transcript_id": row["transcript_id"],
        "tokens": tokens,
        "labels": labels
    })

print("Total rows converted:", len(all_results))

Total rows converted: 2000

In [34]:
from collections import Counter

label_counter = Counter()

for item in all_results:
    label_counter.update(item["labels"])

label_df = pd.DataFrame(
    list(label_counter.items()),
    columns=["Label", "Count"]
).sort_values("Count", ascending=False)

display(label_df)

               Label  Count
0                  O  29298
4            B-STATE   2000
6    B-ANNUAL_INCOME   2000
3       B-OCCUPATION   1690
1              B-AGE   1674
8   B-CASTE_CATEGORY   1017
5            I-STATE    989
9       B-DISABILITY    685
2           B-GENDER    664
7       I-OCCUPATION    476
10      I-DISABILITY    337

In [35]:
from collections import Counter

label_counter = Counter()

for item in all_results:
    label_counter.update(item["labels"])

label_df = pd.DataFrame(
    list(label_counter.items()),
    columns=["Label", "Count"]
).sort_values("Count", ascending=False)

display(label_df)

               Label  Count
0                  O  29298
4            B-STATE   2000
6    B-ANNUAL_INCOME   2000
3       B-OCCUPATION   1690
1              B-AGE   1674
8   B-CASTE_CATEGORY   1017
5            I-STATE    989
9       B-DISABILITY    685
2           B-GENDER    664
7       I-OCCUPATION    476
10      I-DISABILITY    337

In [36]:
def validate_bio(labels):
    errors = []

    for i, label in enumerate(labels):

        if label.startswith("I-"):
            entity = label[2:]

            if i == 0:
                errors.append((i, label))
                continue

            previous = labels[i - 1]

            if previous not in [f"B-{entity}", f"I-{entity}"]:
                errors.append((i, label))

    return errors


invalid_sequences = []

for item in all_results:

    errors = validate_bio(item["labels"])

    if errors:
        invalid_sequences.append({
            "transcript_id": item["transcript_id"],
            "errors": errors
        })


print("Transcripts with invalid BIO sequences:", len(invalid_sequences))

Transcripts with invalid BIO sequences: 0

In [37]:
ner_rows = []

for item in all_results:
    transcript_id = item["transcript_id"]

    for token, label in zip(item["tokens"], item["labels"]):
        ner_rows.append({
            "transcript_id": transcript_id,
            "token": token,
            "label": label
        })

ner_df = pd.DataFrame(ner_rows)

print("Final NER dataset shape:", ner_df.shape)
print("\nColumns:", ner_df.columns.tolist())

display(ner_df.head(25))

Final NER dataset shape: (40830, 3)

Columns: ['transcript_id', 'token', 'label']

   transcript_id      token            label
0          T0001          I                O
1          T0001         am                O
2          T0001          a                O
3          T0001         60            B-AGE
4          T0001       year                O
5          T0001        old                O
6          T0001       male         B-GENDER
7          T0001   berojgar     B-OCCUPATION
8          T0001     living                O
9          T0001         in                O
10         T0001     Madhya          B-STATE
11         T0001    Pradesh          I-STATE
12         T0001         My                O
13         T0001     annual                O
14         T0001  household                O
15         T0001     income                O
16         T0001         is                O
17         T0001     120000  B-ANNUAL_INCOME
18         T0001     rupees                O
19         T0002       Main                O
20         T0002      Uttar          B-STATE
21         T0002    Pradesh          I-STATE
22         T0002         se                O
23         T0002         ek                O
24         T0002      daily     B-OCCUPATION

In [38]:
ner_rows = []

for item in all_results:
    transcript_id = item["transcript_id"]

    for token, label in zip(item["tokens"], item["labels"]):
        ner_rows.append({
            "transcript_id": transcript_id,
            "token": token,
            "label": label
        })

ner_df = pd.DataFrame(ner_rows)

print("Final NER dataset shape:", ner_df.shape)
print("\nColumns:", ner_df.columns.tolist())

display(ner_df.head(25))

Final NER dataset shape: (40830, 3)

Columns: ['transcript_id', 'token', 'label']

   transcript_id      token            label
0          T0001          I                O
1          T0001         am                O
2          T0001          a                O
3          T0001         60            B-AGE
4          T0001       year                O
5          T0001        old                O
6          T0001       male         B-GENDER
7          T0001   berojgar     B-OCCUPATION
8          T0001     living                O
9          T0001         in                O
10         T0001     Madhya          B-STATE
11         T0001    Pradesh          I-STATE
12         T0001         My                O
13         T0001     annual                O
14         T0001  household                O
15         T0001     income                O
16         T0001         is                O
17         T0001     120000  B-ANNUAL_INCOME
18         T0001     rupees                O
19         T0002       Main                O
20         T0002      Uttar          B-STATE
21         T0002    Pradesh          I-STATE
22         T0002         se                O
23         T0002         ek                O
24         T0002      daily     B-OCCUPATION

In [41]:
OUTPUT_PATH = "data/model4_ner_bio_dataset.csv"

ner_df.to_csv(OUTPUT_PATH, index=False)

print(" NER dataset saved successfully!")
print("Location:", OUTPUT_PATH)

 NER dataset saved successfully!
Location: data/model4_ner_bio_dataset.csv